version: "3"

services:
  web:
      container_name: TaskApp
      restart: always
      build: .
      ports:
        - "5000:3000"
      depends_on: 
        - database
  database:
      container_name: mymongodatabase
      image: mongo:latest
      ports:
        - "27018:27017"


